CREATE TABLE IF NOT EXISTS music_universes (
    id INT AUTO_INCREMENT NOT NULL,
    label VARCHAR(180) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    position INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    UNIQUE INDEX UNIQ_MUSIC_UNIVERSES_LABEL (label),
    UNIQUE INDEX UNIQ_MUSIC_UNIVERSES_SLUG (slug),
    INDEX IDX_MUSIC_UNIVERSES_ACTIVE_POSITION (is_active, position),
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

