CREATE TABLE IF NOT EXISTS announcement_ai_moderation_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    announcement_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    post_status_snapshot VARCHAR(20) NOT NULL DEFAULT 'moderation',
    source_transition VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    decision_source VARCHAR(30) DEFAULT NULL,
    decision_code VARCHAR(50) DEFAULT NULL,
    decision_summary VARCHAR(255) DEFAULT NULL,
    ai_model VARCHAR(100) DEFAULT NULL,
    ai_confidence DECIMAL(5,4) DEFAULT NULL,
    payload_snapshot LONGTEXT DEFAULT NULL,
    hard_rules_pass TINYINT(1) DEFAULT NULL,
    ai_pass TINYINT(1) DEFAULT NULL,
    last_error TEXT DEFAULT NULL,
    processed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    INDEX IDX_AAMJ_STATUS_CREATED (status, created_at),
    INDEX IDX_AAMJ_ANNOUNCEMENT_STATUS (announcement_id, status),
    INDEX IDX_AAMJ_USER_STATUS (user_id, status),
    INDEX IDX_AAMJ_PROCESSED_AT (processed_at),
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS announcement_ai_moderation_checks (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    moderation_job_id BIGINT UNSIGNED NOT NULL,
    criterion_code VARCHAR(80) NOT NULL,
    criterion_label VARCHAR(120) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    result VARCHAR(20) NOT NULL,
    score DECIMAL(5,4) DEFAULT NULL,
    reason TEXT DEFAULT NULL,
    raw_value LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    INDEX IDX_AAMC_JOB_ID (moderation_job_id),
    INDEX IDX_AAMC_RESULT (result),
    UNIQUE INDEX UNIQ_AAMC_JOB_CRITERION (moderation_job_id, criterion_code),
    CONSTRAINT FK_AAMC_JOB FOREIGN KEY (moderation_job_id) REFERENCES announcement_ai_moderation_jobs (id) ON DELETE CASCADE,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
